FROM ubuntu
MAINTAINER Jermine.hu@qq.com
ENV CALIBRE_VERSION 3.19.0
RUN apt update -y && apt install -y --no-install-recommends \
    libgl1-mesa-dev ttf-wqy-zenhei fonts-wqy-microhei wget chromium-browser xdg-utils xz-utils ;\
    mkdir -p /opt/calibre && rm -rf /opt/calibre/* && cd /opt/calibre ;\
    wget --no-check-certificate -O  /tmp/calibre-${CALIBRE_VERSION}-x86_64.txz  https://download.calibre-ebook.com/${CALIBRE_VERSION}/calibre-${CALIBRE_VERSION}-x86_64.txz ;\
    tar xvf /tmp/calibre-${CALIBRE_VERSION}-x86_64.txz -C /opt/calibre ;\
    mkdir /usr/share/desktop-directories/ ;\
    /opt/calibre/calibre_postinstall